"""
inject-images.py — Embed screenshots into a Word document generated by textutil.

Usage: update the four variables in the CONFIG section below, then run:
    python3 ~/.claude/skills/product-docs/inject-images.py

How it works:
  1. Reads an existing .docx (generated by textutil from an HTML article).
  2. Finds each numbered step paragraph in the "How to Use It" section.
  3. Inserts a centred image paragraph immediately after each step.
  4. Adds the screenshot files to word/media/ and registers relationships.
  5. Writes a new -final.docx ready to open in Word.

No external dependencies — uses only Python standard library.
"""

import zipfile
import os

# ── CONFIG ──────────────────────────────────────────────────────────────────
DOCX_IN       = '/Users/sambidapradhan/pm-playground/product-docs/FEATURE_SLUG.docx'
DOCX_OUT      = '/Users/sambidapradhan/pm-playground/product-docs/FEATURE_SLUG-final.docx'
SCREENSHOTS_DIR = '/Users/sambidapradhan/pm-playground/product-docs/screenshots/FEATURE_SLUG'
IMAGES = [
    'step-1-DESCRIPTION.png',
    'step-2-DESCRIPTION.png',
    'step-3-DESCRIPTION.png',
    'step-4-DESCRIPTION.png',
    'step-5-DESCRIPTION.png',
]
# ── END CONFIG ───────────────────────────────────────────────────────────────

REL_BASE = 10   # Starting rId number for image relationships

def image_paragraph(step_num, rel_id_str, width_emu=5400000, height_emu=3300000):
    """Return a <w:p> block that embeds an image inline, centred on the page."""
    doc_pr_id = step_num
    return f'''<w:p>
  <w:pPr><w:jc w:val="center"/><w:spacing w:after="200"/></w:pPr>
  <w:r>
    <w:rPr/>
    <w:drawing>
      <wp:inline xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"
                 distT="0" distB="0" distL="0" distR="0">
        <wp:extent cx="{width_emu}" cy="{height_emu}"/>
        <wp:effectExtent l="0" t="0" r="0" b="0"/>
        <wp:docPr id="{doc_pr_id}" name="Image{doc_pr_id}"/>
        <wp:cNvGraphicFramePr>
          <a:graphicFrameLocks xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"
                               noChangeAspect="1"/>
        </wp:cNvGraphicFramePr>
        <a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main">
          <a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture">
            <pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture">
              <pic:nvPicPr>
                <pic:cNvPr id="{doc_pr_id}" name="Image{doc_pr_id}"/>
                <pic:cNvPicPr/>
              </pic:nvPicPr>
              <pic:blipFill>
                <a:blip r:embed="{rel_id_str}"
                        xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"/>
                <a:stretch><a:fillRect/></a:stretch>
              </pic:blipFill>
              <pic:spPr>
                <a:xfrm>
                  <a:off x="0" y="0"/>
                  <a:ext cx="{width_emu}" cy="{height_emu}"/>
                </a:xfrm>
                <a:prstGeom prst="rect"><a:avLst/></a:prstGeom>
              </pic:spPr>
            </pic:pic>
          </a:graphicData>
        </a:graphic>
      </wp:inline>
    </w:drawing>
  </w:r>
</w:p>'''


def inject():
    # Read image bytes
    image_data = {}
    for img in IMAGES:
        path = os.path.join(SCREENSHOTS_DIR, img)
        if not os.path.exists(path):
            print(f"WARNING: screenshot not found — {path}")
            image_data[img] = None
        else:
            with open(path, 'rb') as f:
                image_data[img] = f.read()

    # Read existing docx
    with zipfile.ZipFile(DOCX_IN, 'r') as z:
        files = {name: z.read(name) for name in z.namelist()}

    doc_xml       = files['word/document.xml'].decode('utf-8')
    rels_xml      = files['word/_rels/document.xml.rels'].decode('utf-8')
    content_types = files['[Content_Types].xml'].decode('utf-8')

    # Find How to Use It section
    how_to_idx = doc_xml.find('How to Use It')
    if how_to_idx == -1:
        print("ERROR: 'How to Use It' section not found in document.xml")
        return

    body_end = doc_xml.rfind('</w:body>')
    how_to_section = doc_xml[how_to_idx:body_end]

    # Find closing </w:p> for each numbered step
    step_paragraph_ends = []
    search_from = 0
    for step_num in range(1, len(IMAGES) + 1):
        marker = f'<w:t xml:space="preserve">{step_num}</w:t><w:tab/>'
        pos = how_to_section.find(marker, search_from)
        if pos == -1:
            print(f"WARNING: step {step_num} marker not found — skipping image")
            continue
        end_pos = how_to_section.find('</w:p>', pos)
        if end_pos == -1:
            print(f"WARNING: no closing </w:p> for step {step_num} — skipping image")
            continue
        abs_end = how_to_idx + end_pos + len('</w:p>')
        step_paragraph_ends.append((step_num, abs_end))
        search_from = end_pos + 1
        print(f"Step {step_num}: will insert image after position {abs_end}")

    # Insert image paragraphs from last to first (preserves positions)
    new_doc = doc_xml
    for step_num, insert_pos in reversed(step_paragraph_ends):
        img_idx  = step_num - 1
        rel_id   = f'rId{REL_BASE + img_idx}'
        if image_data.get(IMAGES[img_idx]) is None:
            continue
        para = image_paragraph(step_num, rel_id)
        new_doc = new_doc[:insert_pos] + '\n' + para + new_doc[insert_pos:]
        print(f"Inserted image for step {step_num} (relationship {rel_id})")

    # Add image relationships
    new_rels = rels_xml
    for i, img_name in enumerate(IMAGES):
        if image_data.get(img_name) is None:
            continue
        rel_id    = f'rId{REL_BASE + i}'
        media_ref = f'media/{img_name}'
        entry = (f'<Relationship Id="{rel_id}" '
                 f'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" '
                 f'Target="{media_ref}"/>')
        new_rels = new_rels.replace('</Relationships>', entry + '</Relationships>')

    # Ensure PNG content type is registered
    if 'Extension="png"' not in content_types:
        content_types = content_types.replace(
            '</Types>',
            '<Default Extension="png" ContentType="image/png"/></Types>'
        )

    # Write final docx
    with zipfile.ZipFile(DOCX_OUT, 'w', zipfile.ZIP_DEFLATED) as zout:
        for name, data in files.items():
            if name == 'word/document.xml':
                zout.writestr(name, new_doc.encode('utf-8'))
            elif name == 'word/_rels/document.xml.rels':
                zout.writestr(name, new_rels.encode('utf-8'))
            elif name == '[Content_Types].xml':
                zout.writestr(name, content_types.encode('utf-8'))
            else:
                zout.writestr(name, data)
        for img_name in IMAGES:
            if image_data.get(img_name):
                zout.writestr(f'word/media/{img_name}', image_data[img_name])

    print(f"\nDone — {DOCX_OUT}")


if __name__ == '__main__':
    inject()
